name: monorepo-actions
on:
  workflow_dispatch:
    
jobs:
  build_service_1:
    name: Build Service 1
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: service1
      working-directory: service_1
      run: |
        bash init.sh

  build_service_2:
    name: Build Service 2
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: service1
      working-directory: service_2
      run: |
        bash init.sh

  build_service_3:
    name: Build Service 3
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: service1
      working-directory: service_3
      run: |
        bash init.sh

  build_service_4:
    name: Build Service 4
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: service1
      working-directory: service_4
      run: |
        bash init.sh
