on: push

jobs:

  child-service-1:
    uses: Rahul-Soni28/monorepo-actions/.github/workflows/service_1.yaml@master

  child-service-2:
    uses: Rahul-Soni28/monorepo-actions/.github/workflows/service_2.yaml@master

  child-service-3:
    uses: Rahul-Soni28/monorepo-actions/.github/workflows/service_3.yaml@master

  child-service-4:
    uses: Rahul-Soni28/monorepo-actions/.github/workflows/service_4.yaml@master