name: Parent workflow
on: workflow_dispatch

jobs:

  deployment_env:
    runs-on: ubuntu-latest
    env: 
      branch: $GITHUB_REF_NAME
    steps:
      - name: env
        id: env
        run: |
          if [[ $branch -eq "master" ]]
          then 
            echo "ENVIRONMENT=prod" >> $GITHUB_OUTPUT
          elif [[ $branch -eq "develop" ]] 
          then
            echo "ENVIRONMENT=qa" >> $GITHUB_OUTPUT
          fi



  echo_env:
    runs-on: ubuntu-latest
    steps:
      - name: print env name
        run: |
          echo ${{ jobs.deployment_env.steps.env.outputs.ENVIRONMENT }}

  # child-service-1:
  #   uses: ./.github/workflows/service_1.yaml
  #   with:
  #     branch: $jobs.deployment_env.steps[*].env

  # child-service-2:
  #   uses: ./.github/workflows/service_2.yaml

  # child-service-3:
  #   uses: ./.github/workflows/service_3.yaml

  # child-service-4:
  #   uses: ./.github/workflows/service_4.yaml
