name: service-1
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
     
jobs:
  build_service_1:
    name: Build Service 1
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: service1
      working-directory: service_1
      run: |
        ./init.sh ${{ inputs.branch }}
