name: service-1
on:
  workflow_call:
     
jobs:
  build_service_1:
    name: Build Service 1
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: service1
      working-directory: service_1
      run: |
        bash init.sh
